import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className="grid items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
          {children}
        </main>
      </body>
    </html>
  );
}
